services:
  nocodb:
    image: "nocodb/nocodb:latest"
    depends_on:
      - nocodb-db
      - redis
#      - minio
    security_opt:
      - "no-new-privileges:true"
    environment:
      - "NC_DB=pg://nocodb-db:5432?u=${DATABASE_USER}&p=${DATABASE_PW}&d=${DATABASE_NAME}"
      - "NC_PUBLIC_URL=https://${DOMAIN}"
      - NC_DISABLE_TELE=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nocodb.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.nocodb.entrypoints=websecure"
      - "traefik.http.routers.nocodb.tls.certresolver=http-challenge"
      - "traefik.http.services.nocodb.loadbalancer.server.port=8080"
      #- com.centurylinklabs.watchtower.enable=true
    networks:
      - default
      - traefik-proxy
    restart: always
    volumes:
      - "nocodb-data:/usr/app/data"
  nocodb-db:
    image: "postgres:12.17-alpine"
    security_opt:
      - "no-new-privileges:true"
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_PASSWORD: "${DATABASE_PW}"
      POSTGRES_USER: "${DATABASE_USER}"
    expose:
      - 5432
    healthcheck:
      interval: 10s
      retries: 10
      test: "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"
      timeout: 2s
    restart: always
    volumes:
      - "nocodb-db:/var/lib/postgresql/data"
  redis:
    image: redis:latest
    restart: unless-stopped
    security_opt:
      - "no-new-privileges:true"
    command:
      - /bin/sh
      - -c
#      - redis-server --requirepass "\$\${REDIS_PASSWORD}"
      - redis-server
    healthcheck:
#      test: [ "CMD", "redis-cli", "-a", "\$\${REDIS_PASSWORD}", "--raw", "incr", "ping" ]
      test: [ "CMD", "redis-cli", "-a", "--raw", "incr", "ping" ]
    volumes:
      - "nocodb-redis:/data"
#  minio:
#    image: minio/minio:latest
#    restart: unless-stopped
#    entrypoint: /bin/sh
#    volumes:
#      - "nocodb-minio:/export"
#    command: -c 'mkdir -p /export/nocodb && /usr/bin/minio server /export'
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.services.minio.loadbalancer.server.port=9000"
#      - "traefik.http.routers.minio.rule=Host(`$MINIO_DOMAIN`)"
#      - "traefik.http.routers.minio.entrypoints=websecure"
#  watchtower:
#    command: "--schedule \"0 5 * * *\" --cleanup --label-enable"
#    container_name: watchtower
#    image: containrrr/watchtower
#    labels:
#      - com.centurylinklabs.watchtower.enable=true
#    networks:
#      - traefik_proxy
#    restart: always
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock:ro"
volumes:
  nocodb-data:
    name: nocodb-data
  nocodb-db:
    name: nocodb-db
  nocodb-redis:
    name: nocodb-redis
#  nocodb-minio:
#    name: nocodb-minio
networks:
  default:
  traefik-proxy:
    external: true
